"""All Rapyd enums as Python StrEnum."""

from __future__ import annotations

from enum import StrEnum


class PaymentStatus(StrEnum):
    ACTIVE = "ACT"
    CLOSED = "CLO"
    CANCELED = "CAN"
    ERROR = "ERR"
    EXPIRED = "EXP"
    REVIEWED = "REV"
    NEW = "NEW"


class PaymentMethodCategory(StrEnum):
    CARD = "card"
    CASH = "cash"
    BANK_TRANSFER = "bank_transfer"
    BANK_REDIRECT = "bank_redirect"
    EWALLET = "ewallet"


class PaymentFlowType(StrEnum):
    DIRECT = "direct"
    REDIRECT = "redirect"
    EWALLET_PAYER = "ewallet_payer"


class NextAction(StrEnum):
    THREE_DS_VERIFICATION = "3d_verification"
    PENDING_CONFIRMATION = "pending_confirmation"
    PENDING_CAPTURE = "pending_capture"
    NOT_APPLICABLE = "not_applicable"


class RefundStatus(StrEnum):
    PENDING = "Pending"
    COMPLETED = "Completed"
    CANCELED = "Canceled"
    ERROR = "Error"
    REJECTED = "Rejected"


class DisputeStatus(StrEnum):
    ACTIVE = "ACT"
    REVIEW = "RVW"
    PRE_ARBITRATION = "PRA"
    ARBITRATION = "ARB"
    LOSS = "LOS"
    WIN = "WIN"
    REVERSE = "REV"


class PayoutStatus(StrEnum):
    CREATED = "Created"
    CONFIRMATION = "Confirmation"
    COMPLETED = "Completed"
    CANCELED = "Canceled"
    ERROR = "Error"
    EXPIRED = "Expired"
    RETURNED = "Returned"


class PayoutMethodCategory(StrEnum):
    BANK = "bank"
    CASH = "cash"
    CARD = "card"
    EWALLET = "ewallet"
    RAPYD_WALLET = "rapyd_ewallet"


class SubscriptionStatus(StrEnum):
    ACTIVE = "active"
    CANCELED = "canceled"
    PAST_DUE = "past_due"
    TRIALING = "trialing"
    UNPAID = "unpaid"


class InvoiceStatus(StrEnum):
    DRAFT = "draft"
    OPEN = "open"
    PAID = "paid"
    UNCOLLECTIBLE = "uncollectible"
    VOID = "void"


class WebhookStatus(StrEnum):
    NEW = "NEW"
    RESENT = "RET"
    CLOSED = "CLO"
    ERROR = "ERR"


class CardStatus(StrEnum):
    ACTIVE = "ACT"
    INACTIVE = "INA"
    BLOCKED = "BLO"
    EXPIRED = "EXP"


class CardBlockReasonCode(StrEnum):
    STOLEN = "STO"
    LOST = "LOS"
    FRAUD = "FRD"
    CANCELED = "CAN"
    LOCKED = "LOC"


class EntityType(StrEnum):
    INDIVIDUAL = "individual"
    COMPANY = "company"


class FeeCalcType(StrEnum):
    NET = "net"
    GROSS = "gross"


class FixedSide(StrEnum):
    BUY = "buy"
    SELL = "sell"


class WalletContactType(StrEnum):
    PERSONAL = "personal"
    BUSINESS = "business"


class CouponDuration(StrEnum):
    FOREVER = "forever"
    REPEATING = "repeating"
    ONCE = "once"


class PlanInterval(StrEnum):
    DAY = "day"
    WEEK = "week"
    MONTH = "month"
    YEAR = "year"


class CheckoutPageStatus(StrEnum):
    NEW = "NEW"
    DONE = "DON"
    EXPIRED = "EXP"


class EscrowStatus(StrEnum):
    PENDING = "pending"
    RELEASED = "released"
    PARTIALLY_RELEASED = "partially_released"


class IssuingTxnType(StrEnum):
    SALE = "SALE"
    CREDIT = "CREDIT"
    REVERSAL = "REVERSAL"
    REFUND = "REFUND"
    CHARGEBACK = "CHARGEBACK"
    ADJUSTMENT = "ADJUSTMENT"
    ATM_FEE = "ATM_FEE"
    ATM_WITHDRAWAL = "ATM_WITHDRAWAL"


class Environment(StrEnum):
    SANDBOX = "sandbox"
    PRODUCTION = "production"


class WebhookEventType(StrEnum):
    # Payments
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_EXPIRED = "PAYMENT_EXPIRED"
    PAYMENT_UPDATED = "PAYMENT_UPDATED"
    PAYMENT_CAPTURED = "PAYMENT_CAPTURED"
    PAYMENT_CANCELED = "PAYMENT_CANCELED"
    PAYMENT_REFUND_COMPLETED = "PAYMENT_REFUND_COMPLETED"
    PAYMENT_REFUND_FAILED = "PAYMENT_REFUND_FAILED"
    PAYMENT_REFUND_REJECTED = "PAYMENT_REFUND_REJECTED"
    PAYMENT_DISPUTE_CREATED = "PAYMENT_DISPUTE_CREATED"
    PAYMENT_DISPUTE_UPDATED = "PAYMENT_DISPUTE_UPDATED"
    # Refunds
    REFUND_COMPLETED = "REFUND_COMPLETED"
    REFUND_FAILED = "REFUND_FAILED"
    REFUND_REJECTED = "REFUND_REJECTED"
    # Customers
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"
    CUSTOMER_DELETED = "CUSTOMER_DELETED"
    CUSTOMER_PAYMENT_METHOD_CREATED = "CUSTOMER_PAYMENT_METHOD_CREATED"
    CUSTOMER_PAYMENT_METHOD_UPDATED = "CUSTOMER_PAYMENT_METHOD_UPDATED"
    CUSTOMER_PAYMENT_METHOD_DELETED = "CUSTOMER_PAYMENT_METHOD_DELETED"
    CUSTOMER_PAYMENT_METHOD_EXPIRING = "CUSTOMER_PAYMENT_METHOD_EXPIRING"
    # Subscriptions
    CUSTOMER_SUBSCRIPTION_CREATED = "CUSTOMER_SUBSCRIPTION_CREATED"
    CUSTOMER_SUBSCRIPTION_UPDATED = "CUSTOMER_SUBSCRIPTION_UPDATED"
    CUSTOMER_SUBSCRIPTION_COMPLETED = "CUSTOMER_SUBSCRIPTION_COMPLETED"
    CUSTOMER_SUBSCRIPTION_CANCELED = "CUSTOMER_SUBSCRIPTION_CANCELED"
    CUSTOMER_SUBSCRIPTION_PAST_DUE = "CUSTOMER_SUBSCRIPTION_PAST_DUE"
    CUSTOMER_SUBSCRIPTION_TRIAL_END = "CUSTOMER_SUBSCRIPTION_TRIAL_END"
    CUSTOMER_SUBSCRIPTION_RENEWED = "CUSTOMER_SUBSCRIPTION_RENEWED"
    # Invoices
    INVOICE_CREATED = "INVOICE_CREATED"
    INVOICE_UPDATED = "INVOICE_UPDATED"
    INVOICE_PAYMENT_CREATED = "INVOICE_PAYMENT_CREATED"
    INVOICE_PAYMENT_SUCCEEDED = "INVOICE_PAYMENT_SUCCEEDED"
    INVOICE_PAYMENT_FAILED = "INVOICE_PAYMENT_FAILED"
    # Payouts
    PAYOUT_COMPLETED = "PAYOUT_COMPLETED"
    PAYOUT_UPDATED = "PAYOUT_UPDATED"
    PAYOUT_FAILED = "PAYOUT_FAILED"
    PAYOUT_EXPIRED = "PAYOUT_EXPIRED"
    PAYOUT_CANCELED = "PAYOUT_CANCELED"
    PAYOUT_RETURNED = "PAYOUT_RETURNED"
    # Wallet
    WALLET_TRANSACTION = "WALLET_TRANSACTION"
    WALLET_FUNDS_ADDED = "WALLET_FUNDS_ADDED"
    WALLET_FUNDS_REMOVED = "WALLET_FUNDS_REMOVED"
    WALLET_TRANSFER_COMPLETED = "WALLET_TRANSFER_COMPLETED"
    WALLET_TRANSFER_FAILED = "WALLET_TRANSFER_FAILED"
    WALLET_TRANSFER_RESPONSE_RECEIVED = "WALLET_TRANSFER_RESPONSE_RECEIVED"
    # Card Issuing
    CARD_ISSUING_AUTHORIZATION_APPROVED = "CARD_ISSUING_AUTHORIZATION_APPROVED"
    CARD_ISSUING_AUTHORIZATION_DECLINED = "CARD_ISSUING_AUTHORIZATION_DECLINED"
    CARD_ISSUING_SALE = "CARD_ISSUING_SALE"
    CARD_ISSUING_CREDIT = "CARD_ISSUING_CREDIT"
    CARD_ISSUING_REVERSAL = "CARD_ISSUING_REVERSAL"
    CARD_ISSUING_REFUND = "CARD_ISSUING_REFUND"
    CARD_ISSUING_CHARGEBACK = "CARD_ISSUING_CHARGEBACK"
    CARD_ISSUING_ADJUSTMENT = "CARD_ISSUING_ADJUSTMENT"
    CARD_ISSUING_ATM_FEE = "CARD_ISSUING_ATM_FEE"
    CARD_ISSUING_ATM_WITHDRAWAL = "CARD_ISSUING_ATM_WITHDRAWAL"
    CARD_ADDED_SUCCESSFULLY = "CARD_ADDED_SUCCESSFULLY"
    CARD_ISSUING_TRANSACTION_COMPLETED = "CARD_ISSUING_TRANSACTION_COMPLETED"
    # Verify
    VERIFY_APPLICATION_SUBMITTED = "VERIFY_APPLICATION_SUBMITTED"
    VERIFY_APPLICATION_APPROVED = "VERIFY_APPLICATION_APPROVED"
    VERIFY_APPLICATION_REJECTED = "VERIFY_APPLICATION_REJECTED"
    # Virtual Accounts
    VIRTUAL_ACCOUNT_CREATED = "VIRTUAL_ACCOUNT_CREATED"
    VIRTUAL_ACCOUNT_UPDATED = "VIRTUAL_ACCOUNT_UPDATED"
    VIRTUAL_ACCOUNT_CLOSED = "VIRTUAL_ACCOUNT_CLOSED"
    VIRTUAL_ACCOUNT_TRANSACTION = "VIRTUAL_ACCOUNT_TRANSACTION"
